In [1]:
import numpy as np

Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [3]:
def alex_theo_matrix(inp_vec,n, increasing=False):
    if not increasing:
        op_mat = np.array([x**(n-1-a) for x in inp_vec for a in range(n)]).reshape(inp_vec.size,n)
    elif increasing:
        op_mat = np.array([x**a for x in inp_vec for a in range(n)]).reshape(inp_vec.size,n)
        
    return op_mat

print('-----OUTPUT-----')
inp_vec = np.array([1,2,3,4,5])
nocol_opmat = 5
dec_order_mat = alex_theo_matrix(inp_vec,nocol_opmat,False)
inc_order_mat = alex_theo_matrix(inp_vec,nocol_opmat,True)

print("The input array is:",inp_vec,"\n")
print("Number of columns in output matrix should be:",nocol_opmat,"\n")
print("Alexandre-Theophile Vandermonde matrix of the input array in decreasing order of powers:\n\n",dec_order_mat,"\n")
print("Alexandre-Theophile Vandermonde matrix of the input array in increasing order of powers:\n\n",inc_order_mat,"\n")

-----OUTPUT-----
The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 5 

Alexandre-Theophile Vandermonde matrix of the input array in decreasing order of powers:

 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]] 

Alexandre-Theophile Vandermonde matrix of the input array in increasing order of powers:

 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]] 



Problem Statement 2

Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [6]:
import numpy as np

def moving_avg(inp_arr, k=3) :
    input_arrshape = inp_arr.shape[0]
    
    #Create a vector of zeroes with the shape as n-k+1
    
    outarr_movingavg = np.zeros(input_arrshape - k + 1)
    
    # Iterate over the input array. While doing so, for every element, get the next k elements through slicing, 
    # computer their mean and add to the output array.
    
    for i in range(k, input_arrshape + 1):
        outarr_movingavg[i-k] = inp_arr[i-k:i].mean()
    
    return outarr_movingavg    


arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
win_size = 3
moving_average_arr = moving_avg(arr, win_size)

print("The input sequence is =", arr, "\n")
print("The moving average of the sequence with the rolling window size", win_size, "is =\n", moving_average_arr, "\n")
print("The moving average sequence should have", arr.shape[0] - win_size + 1, "values.\n")
print("The moving average sequence has", moving_average_arr.shape[0], "values.")

The input sequence is = [  3   5   7   2   8  10  11  65  72  81  99 100 150] 

The moving average of the sequence with the rolling window size 3 is =
 [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333] 

The moving average sequence should have 11 values.

The moving average sequence has 11 values.
